<<<<<<< HEAD
# Generated by Django 2.0.5 on 2020-07-16 14:52
=======
# Generated by Django 2.0.5 on 2020-07-16 19:33
>>>>>>> master

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
>>>>>>> master
                ('nombre_depa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
>>>>>>> master
                ('nombre_muni', models.CharField(max_length=30)),
                ('departamento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interStop_app.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('sector', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
=======
                ('id_sectorp', models.CharField(max_length=3)),
                ('fecha', models.DateField()),
                ('id_problemap', models.CharField(max_length=3)),
                ('id_departamentop', models.CharField(max_length=3)),
                ('id_municipiop', models.CharField(max_length=3)),
                ('id_usuariop', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaDes',
            fields=[
                ('id_problema', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('problema_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sector_afectado',
            fields=[
                ('id_sector', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('sector_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='testprueba',
            fields=[
                ('id_ubicaciont', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('id_municipiot', models.CharField(max_length=5)),
                ('id_departamentot', models.CharField(max_length=5)),
>>>>>>> master
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.CharField(max_length=5, primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('municipio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interStop_app.Municipio')),
=======
                ('id_departamento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interStop_app.Departamento')),
                ('id_municipio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interStop_app.Municipio')),
>>>>>>> master
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=10)),
            ],
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='problema',
            name='ubicacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interStop_app.Ubicacion'),
        ),
        migrations.AddField(
            model_name='problema',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interStop_app.Usuario'),
        ),
=======
>>>>>>> master
    ]
