# Generated by Django 2.0.5 on 2020-07-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_depa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_muni', models.CharField(max_length=30)),
                ('departamento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interStop_app.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('municipio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interStop_app.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='problema',
            name='ubicacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interStop_app.Ubicacion'),
        ),
        migrations.AddField(
            model_name='problema',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interStop_app.Usuario'),
        ),
    ]
